[build]
  base = "client"
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # Set next target to output standalone for better optimizations
  # NEXT_PUBLIC_API_URL = "https://athlixir-server.onrender.com"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
